# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3052afae58b177d977d69c58bd70564e97286ab71ac7ebb5497af0657f38eac7b6f0b1e246e23d5590bab1e1b0a360c8ff094d17d40bc1fc1a004372e6f53169

test:
  secret_key_base: 2634c39fbe11c80f25376f5f7bf0788de273faea6620e89941a07ec4051442981fed26158c6d28865e2ffea5a5347b8c3cb6ba7118df87f89d72c95607ac87fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
